# Generated by Django 6.0.2 on 2026-02-27 13:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('fr', 'Français'), ('nl', 'Nederlands'), ('ru', 'Русский')], default='fr', max_length=5, verbose_name='Langue')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Avatar')),
                ('bio', models.TextField(blank=True, verbose_name='Bio')),
                ('is_premium', models.BooleanField(default=False, verbose_name='Premium')),
                ('premium_until', models.DateTimeField(blank=True, null=True, verbose_name="Premium jusqu'à")),
                ('total_questions_answered', models.IntegerField(default=0, verbose_name='Questions répondues')),
                ('correct_answers', models.IntegerField(default=0, verbose_name='Réponses correctes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil utilisateur',
                'verbose_name_plural': 'Profils utilisateurs',
            },
        ),
        migrations.CreateModel(
            name='DailyQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('questions_answered', models.IntegerField(default=0, verbose_name='Questions répondues')),
                ('max_questions', models.IntegerField(default=15, verbose_name='Maximum questions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_quotas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quota quotidien',
                'verbose_name_plural': 'Quotas quotidiens',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
