# Generated by Django 5.2.8 on 2025-11-28 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category_tag_alter_article_meta_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(choices=[('purple', 'Purple'), ('blue', 'Blue'), ('green', 'Green'), ('yellow', 'Yellow'), ('red', 'Red'), ('pink', 'Pink'), ('indigo', 'Indigo'), ('orange', 'Orange')], default='purple', help_text='Color for category badge', max_length=20),
        ),
    ]
