# Generated by Django 5.2.8 on 2025-12-03 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_category_color'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='profile_author',
            field=models.ForeignKey(blank=True, help_text='Author profile (if available)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='profiles.profile'),
        ),
        migrations.DeleteModel(
            name='ArticleFAQ',
        ),
    ]
