# Generated by Django 5.2.8 on 2025-12-05 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_article_profile_author_delete_articlefaq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='keywords',
        ),
    ]
