# Generated by Django 5.2.8 on 2025-12-06 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_keywords_field'),
        ('profiles', '0009_remove_productcategory_icon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(help_text='Name (required for non-registered users)', max_length=100)),
                ('author_email', models.EmailField(help_text='Email (required for non-registered users)', max_length=254)),
                ('comment', models.TextField(help_text='Comment text (max 2000 characters)', max_length=2000)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté')], db_index=True, default='pending', max_length=20)),
                ('moderation_note', models.TextField(blank=True, help_text='Internal note for moderators')),
                ('moderated_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(help_text='IP address of commenter')),
                ('user_agent', models.CharField(blank=True, help_text='Browser user agent', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('edited_at', models.DateTimeField(blank=True, help_text='When comment was last edited by author', null=True)),
                ('likes_count', models.PositiveIntegerField(default=0, help_text='Number of likes')),
                ('article', models.ForeignKey(help_text='Article being commented on', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.article')),
                ('author_profile', models.ForeignKey(blank=True, help_text='Profile if user is registered', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_comments', to='profiles.profile')),
                ('moderated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_comments', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, help_text='Parent comment for nested replies', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blog.articlecomment')),
            ],
            options={
                'verbose_name': 'Article Comment',
                'verbose_name_plural': 'Article Comments',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['article', 'status', 'created_at'], name='blog_articl_article_eadae4_idx'), models.Index(fields=['status', 'created_at'], name='blog_articl_status_0513c5_idx')],
            },
        ),
    ]
