# Generated by Django 5.2.8 on 2025-12-06 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_articlelike'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_page',
            field=models.BooleanField(default=False, help_text="Check if this is a technical page (won't appear in blog listing)", verbose_name='Technical page'),
        ),
    ]
