# Generated by Django 5.2.8 on 2025-12-06 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_article_is_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, help_text='Brief description shown at the top of category page (2-3 sentences)', verbose_name='Short description'),
        ),
        migrations.AddField(
            model_name='category',
            name='seo_text',
            field=models.TextField(blank=True, help_text='Detailed SEO text shown at the bottom of category page (200-400 words for better Google indexing)', verbose_name='SEO content'),
        ),
    ]
