# Generated by Django 5.2.8 on 2025-12-07 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_category_description_category_seo_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='featured_order',
            field=models.IntegerField(default=0, help_text='Order for featured articles (lower numbers appear first, 0 = not featured)', verbose_name='Featured order'),
        ),
        migrations.AddField(
            model_name='article',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Featured articles appear at the top of listings with special styling', verbose_name='Featured article'),
        ),
    ]
