# Generated by Django 5.2.8 on 2025-12-07 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_article_featured_order_article_is_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Series title')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField(help_text='Brief description of what this series covers', verbose_name='Series description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Article Series',
                'verbose_name_plural': 'Article Series',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='series_order',
            field=models.IntegerField(default=0, help_text='Position in the series (1 = first, 2 = second, etc.)', verbose_name='Order in series'),
        ),
        migrations.AddField(
            model_name='article',
            name='series',
            field=models.ForeignKey(blank=True, help_text='Part of a series (e.g., tutorial series)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='blog.articleseries', verbose_name='Article series'),
        ),
    ]
