# Generated by Django 5.2.8 on 2025-12-07 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_articleseries_article_series_order_article_series'),
        ('profiles', '0012_alter_play_options_alter_playauthorrole_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='recommended_products',
            field=models.ManyToManyField(blank=True, help_text='Produits recommandés pour cet article (max 4-6)', related_name='recommended_in_articles', to='profiles.play'),
        ),
    ]
