# Generated by Django 5.2.8 on 2025-12-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_article_recommended_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='color',
        ),
        migrations.AddField(
            model_name='category',
            name='color_bg',
            field=models.CharField(default='#f3e8ff', help_text='Background color (hex format, e.g., #f3e8ff)', max_length=7),
        ),
        migrations.AddField(
            model_name='category',
            name='color_text',
            field=models.CharField(default='#7c3aed', help_text='Text color (hex format, e.g., #7c3aed)', max_length=7),
        ),
    ]
