# Generated by Django 5.2.8 on 2025-12-08 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_remove_category_color_category_color_bg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlelike',
            name='session_key',
            field=models.CharField(blank=True, help_text='Session key for anonymous users', max_length=40, null=True),
        ),
    ]
