# Generated by Django 5.2.8 on 2025-12-11 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_articlelike_session_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Blog', max_length=200, verbose_name='Page Title (H1)')),
                ('header_text', models.TextField(blank=True, help_text='Short introduction text displayed at the top of the blog page (2-3 sentences)', verbose_name='Header Description')),
                ('footer_text', models.TextField(blank=True, help_text='Detailed description displayed at the bottom of the blog page (200-300 words, with keywords)', verbose_name='Footer SEO Text')),
                ('meta_title', models.CharField(blank=True, help_text='SEO meta title for blog page', max_length=200, verbose_name='Meta Title')),
                ('meta_description', models.TextField(blank=True, help_text='SEO meta description for blog page', max_length=300, verbose_name='Meta Description')),
            ],
            options={
                'verbose_name': 'Blog Settings',
                'verbose_name_plural': 'Blog Settings',
            },
        ),
    ]
