# Generated by Django 5.2.8 on 2025-12-11 06:38

from django.db import migrations


def migrate_author_to_profile(apps, schema_editor):
    """
    Migrate author (User) to profile_author (Profile).
    If article has author but no profile_author, try to find the user's profile.
    """
    Article = apps.get_model('blog', 'Article')

    migrated_count = 0
    for article in Article.objects.filter(author__isnull=False, profile_author__isnull=True):
        # Try to get the user's profile
        user = article.author
        try:
            # Access profile via reverse relation (assuming User has profile)
            if hasattr(user, 'author_profile'):
                article.profile_author = user.author_profile
                article.save(update_fields=['profile_author'])
                migrated_count += 1
        except Exception:
            # If no profile exists, skip this article
            pass

    print(f"Migrated {migrated_count} articles from author to profile_author")


def reverse_migration(apps, schema_editor):
    """Reverse migration - restore author from profile_author if needed."""
    Article = apps.get_model('blog', 'Article')

    for article in Article.objects.filter(profile_author__isnull=False, author__isnull=True):
        try:
            # Try to get user from profile
            if hasattr(article.profile_author, 'user'):
                article.author = article.profile_author.user
                article.save(update_fields=['author'])
        except Exception:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_blogsettings'),
    ]

    operations = [
        migrations.RunPython(migrate_author_to_profile, reverse_migration),
    ]
