# Generated by Django 5.2.8 on 2025-12-11 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_migrate_author_to_profile'),
        ('profiles', '0013_profile_email_verified_emailverificationtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
        migrations.AlterField(
            model_name='article',
            name='profile_author',
            field=models.ForeignKey(blank=True, help_text='Article author (leave empty for technical pages)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='profiles.profile', verbose_name='Author'),
        ),
    ]
