# Generated by Django 5.2.8 on 2025-12-11 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_remove_article_author_alter_article_profile_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('review', 'Review'), ('published', 'Published'), ('scheduled', 'Scheduled')], default='draft', max_length=20),
        ),
    ]
