# Generated by Django 5.2.8 on 2026-02-09 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_add_review_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('review', 'Review'), ('published', 'Published')], default='draft', max_length=20),
        ),
    ]
