from django.contrib.auth.models import User
from django.test import TestCase
from django.urls import reverse
from django.utils import timezone

from .models import BlogPost


# ─── Helpers ──────────────────────────────────────────────────────────────────

def make_user(username='bloguser', password='testpass123'):
    return User.objects.create_user(username=username, password=password)


def make_post(author, title='Test Article', slug='test-article',
              content='Contenu.', is_published=True):
    post = BlogPost.objects.create(
        author=author,
        title=title,
        slug=slug,
        content=content,
        is_published=is_published,
    )
    return post


# ─── BlogPost.save() logic ───────────────────────────────────────────────────

class BlogPostSaveTests(TestCase):

    def setUp(self):
        self.user = make_user()

    def test_read_time_200_words(self):
        content = ' '.join(['mot'] * 200)
        post = make_post(self.user, content=content, slug='read-200')
        self.assertEqual(post.read_time, 1)

    def test_read_time_400_words(self):
        content = ' '.join(['mot'] * 400)
        post = make_post(self.user, content=content, slug='read-400')
        self.assertEqual(post.read_time, 2)

    def test_read_time_minimum_one(self):
        post = make_post(self.user, content='Court.', slug='read-short')
        self.assertEqual(post.read_time, 1)

    def test_published_at_set_on_first_publish(self):
        post = make_post(self.user, is_published=True, slug='pub-first')
        self.assertIsNotNone(post.published_at)

    def test_published_at_not_overwritten_on_resave(self):
        post = make_post(self.user, is_published=True, slug='pub-nosave')
        original_published_at = post.published_at
        post.content = 'Contenu modifié.'
        post.save()
        post.refresh_from_db()
        self.assertEqual(post.published_at, original_published_at)

    def test_slug_autogenerated_from_title(self):
        post = BlogPost.objects.create(
            author=self.user,
            title='Mon super article',
            content='...',
            is_published=False,
        )
        self.assertEqual(post.slug, 'mon-super-article')

    def test_explicit_slug_preserved(self):
        post = make_post(self.user, slug='mon-slug-perso')
        self.assertEqual(post.slug, 'mon-slug-perso')


# ─── Blog views ───────────────────────────────────────────────────────────────

class BlogPostListViewTests(TestCase):

    def setUp(self):
        self.user = make_user('listblog')

    def test_list_returns_200(self):
        response = self.client.get(reverse('blog:list'))
        self.assertEqual(response.status_code, 200)

    def test_unpublished_not_visible(self):
        make_post(self.user, slug='hidden-post', is_published=False)
        response = self.client.get(reverse('blog:list'))
        # Post names shouldn't appear in the page content
        self.assertNotContains(response, 'hidden-post')


class BlogPostDetailViewTests(TestCase):

    def setUp(self):
        self.user = make_user('detailblog')

    def test_published_post_returns_200(self):
        post = make_post(self.user, slug='public-post')
        response = self.client.get(reverse('blog:detail', kwargs={'slug': post.slug}))
        self.assertEqual(response.status_code, 200)

    def test_unpublished_post_returns_404(self):
        post = make_post(self.user, slug='secret-post', is_published=False)
        response = self.client.get(reverse('blog:detail', kwargs={'slug': post.slug}))
        self.assertEqual(response.status_code, 404)

    def test_nonexistent_slug_returns_404(self):
        response = self.client.get(reverse('blog:detail', kwargs={'slug': 'nope'}))
        self.assertEqual(response.status_code, 404)


class BlogSearchViewTests(TestCase):

    def setUp(self):
        self.user = make_user('searchblog')

    def test_empty_query_returns_200_no_crash(self):
        response = self.client.get(reverse('blog:search'), {'q': ''})
        self.assertEqual(response.status_code, 200)

    def test_matching_query_finds_post(self):
        make_post(self.user, title='Article sur la vitesse', slug='vitesse')
        response = self.client.get(reverse('blog:search'), {'q': 'vitesse'})
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, 'vitesse')

    def test_no_match_returns_empty(self):
        response = self.client.get(reverse('blog:search'), {'q': 'xyzinexistant'})
        self.assertEqual(response.status_code, 200)
