# Generated by Django 6.0.2 on 2026-02-27 13:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reglementation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nom (FR)')),
                ('name_nl', models.CharField(blank=True, max_length=150, verbose_name='Naam (NL)')),
                ('name_ru', models.CharField(blank=True, max_length=150, verbose_name='Название (RU)')),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Icône')),
                ('description', models.TextField(blank=True, verbose_name='Description (FR)')),
                ('description_nl', models.TextField(blank=True, verbose_name='Beschrijving (NL)')),
                ('description_ru', models.TextField(blank=True, verbose_name='Описание (RU)')),
                ('order', models.IntegerField(default=0, verbose_name='Ordre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Catégorie examen',
                'verbose_name_plural': 'Catégories examen',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Question (FR)')),
                ('text_nl', models.TextField(blank=True, verbose_name='Vraag (NL)')),
                ('text_ru', models.TextField(blank=True, verbose_name='Вопрос (RU)')),
                ('image', models.ImageField(blank=True, upload_to='questions/', verbose_name='Image')),
                ('explanation', models.TextField(blank=True, verbose_name='Explication (FR)')),
                ('explanation_nl', models.TextField(blank=True, verbose_name='Uitleg (NL)')),
                ('explanation_ru', models.TextField(blank=True, verbose_name='Объяснение (RU)')),
                ('difficulty', models.IntegerField(choices=[(1, 'Facile'), (2, 'Moyen'), (3, 'Difficile')], default=2, verbose_name='Difficulté')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('is_official', models.BooleanField(default=False, help_text="Provient d'un examen officiel", verbose_name='Question officielle')),
                ('source', models.CharField(blank=True, max_length=200, verbose_name='Source')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='Tags')),
                ('times_answered', models.IntegerField(default=0, verbose_name='Fois répondu')),
                ('times_correct', models.IntegerField(default=0, verbose_name='Fois correct')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='examens.examcategory', verbose_name='Catégorie')),
                ('code_article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='reglementation.codearticle', verbose_name='Article du code')),
                ('traffic_sign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='reglementation.trafficsign', verbose_name='Panneau')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['category', 'difficulty', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnswerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(help_text='A, B, C, D', max_length=2, verbose_name='Lettre')),
                ('text', models.CharField(max_length=500, verbose_name='Réponse (FR)')),
                ('text_nl', models.CharField(blank=True, max_length=500, verbose_name='Antwoord (NL)')),
                ('text_ru', models.CharField(blank=True, max_length=500, verbose_name='Ответ (RU)')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Correcte')),
                ('order', models.IntegerField(default=0, verbose_name='Ordre')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='examens.question', verbose_name='Question')),
            ],
            options={
                'verbose_name': 'Option de réponse',
                'verbose_name_plural': 'Options de réponse',
                'ordering': ['order', 'letter'],
            },
        ),
        migrations.CreateModel(
            name='TestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('test_type', models.CharField(choices=[('practice', 'Entraînement'), ('exam', 'Examen simulé')], default='practice', max_length=20, verbose_name='Type')),
                ('answers_data', models.JSONField(default=list, verbose_name='Données des réponses')),
                ('score', models.IntegerField(default=0, verbose_name='Score')),
                ('total_questions', models.IntegerField(default=0, verbose_name='Total questions')),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Pourcentage')),
                ('passed', models.BooleanField(default=False, verbose_name='Réussi')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Début')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fin')),
                ('time_spent', models.IntegerField(default=0, verbose_name='Temps (sec)')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempts', to='examens.examcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tentative de test',
                'verbose_name_plural': 'Tentatives de test',
                'ordering': ['-started_at'],
            },
        ),
    ]
