# Generated by Django 6.0.2 on 2026-03-02 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image_prompt',
            field=models.TextField(blank=True, help_text="Description pour génération d'image (AI)", verbose_name='Prompt image'),
        ),
    ]
