# Generated by Django 6.0.2 on 2026-03-02 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examens', '0002_question_image_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image_sign_code',
            field=models.CharField(blank=True, help_text="Ex: C43, F5 — panneau suggéré pour l'image", max_length=20, verbose_name='Code panneau'),
        ),
    ]
