# Generated by Django 6.0.2 on 2026-03-04 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examens', '0003_question_image_sign_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('icon', models.CharField(default='📌', max_length=10, verbose_name='Icône (emoji)')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Description')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Ordre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Liste de révision',
                'verbose_name_plural': 'Listes de révision',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SavedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True, verbose_name='Sauvegardé le')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='examens.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_questions', to=settings.AUTH_USER_MODEL)),
                ('study_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_questions', to='examens.studylist')),
            ],
            options={
                'verbose_name': 'Question sauvegardée',
                'verbose_name_plural': 'Questions sauvegardées',
                'ordering': ['-saved_at'],
                'unique_together': {('user', 'question', 'study_list')},
            },
        ),
    ]
