# Generated by Django 6.0.2 on 2026-03-04 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examens', '0004_studylist_savedquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image_alt',
            field=models.CharField(blank=True, help_text="Texte alternatif pour l'image (SEO & accessibilité)", max_length=200, verbose_name='Alt image'),
        ),
        migrations.AddField(
            model_name='question',
            name='image_caption',
            field=models.CharField(blank=True, help_text="Texte affiché sous l'image", max_length=300, verbose_name='Légende image'),
        ),
    ]
