# Generated by Django 6.0.2 on 2026-02-27 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom (FR)')),
                ('name_nl', models.CharField(blank=True, max_length=100, verbose_name='Naam (NL)')),
                ('name_ru', models.CharField(blank=True, max_length=100, verbose_name='Название (RU)')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('order', models.IntegerField(default=0, verbose_name='Ordre')),
            ],
            options={
                'verbose_name': 'Catégorie blog',
                'verbose_name_plural': 'Catégories blog',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre (FR)')),
                ('content', models.TextField(verbose_name='Contenu (FR)')),
                ('excerpt', models.CharField(blank=True, max_length=300, verbose_name='Extrait (FR)')),
                ('title_nl', models.CharField(blank=True, max_length=200, verbose_name='Titel (NL)')),
                ('content_nl', models.TextField(blank=True, verbose_name='Inhoud (NL)')),
                ('excerpt_nl', models.CharField(blank=True, max_length=300, verbose_name='Uittreksel (NL)')),
                ('title_ru', models.CharField(blank=True, max_length=200, verbose_name='Заголовок (RU)')),
                ('content_ru', models.TextField(blank=True, verbose_name='Содержание (RU)')),
                ('excerpt_ru', models.CharField(blank=True, max_length=300, verbose_name='Отрывок (RU)')),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('featured_image', models.ImageField(blank=True, upload_to='blog/', verbose_name='Image principale')),
                ('featured_image_alt', models.CharField(blank=True, max_length=200, verbose_name='Alt image')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publié')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de publication')),
                ('views_count', models.IntegerField(default=0, verbose_name='Vues')),
                ('read_time', models.IntegerField(default=5, verbose_name='Temps de lecture (min)')),
                ('meta_title', models.CharField(blank=True, help_text="Max 70 caractères. Vide = titre de l'article.", max_length=70, verbose_name='Meta title')),
                ('meta_description', models.CharField(blank=True, help_text='Max 160 caractères. Vide = extrait.', max_length=160, verbose_name='Meta description')),
                ('keywords', models.CharField(blank=True, help_text='Séparés par des virgules.', max_length=300, verbose_name='Mots-clés')),
                ('canonical_url', models.URLField(blank=True, help_text="Laisser vide pour utiliser l'URL par défaut.", verbose_name='URL canonique')),
                ('no_index', models.BooleanField(default=False, help_text="Empêcher l'indexation par les moteurs de recherche.", verbose_name='No index')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.blogcategory')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-published_at'],
            },
        ),
    ]
