# Generated by Django 6.0.2 on 2026-03-04 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='og_description',
            field=models.CharField(blank=True, help_text='Open Graph description. Vide = meta_description.', max_length=300, verbose_name='OG description'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='og_title',
            field=models.CharField(blank=True, help_text='Open Graph title (Facebook/LinkedIn). Vide = meta_title.', max_length=200, verbose_name='OG title'),
        ),
    ]
