# Generated by Django 6.0.2 on 2026-03-04 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_add_og_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='featured_image_caption',
            field=models.CharField(blank=True, help_text="Texte affiché sous l'image (figcaption). Bon pour le SEO.", max_length=300, verbose_name='Légende image'),
        ),
    ]
