# Generated by Django 6.0.2 on 2026-03-05 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KeySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='🔑', help_text='Emoji ou caractère affiché comme monnaie', max_length=10, verbose_name='Icône')),
                ('currency_plural', models.CharField(default='clés', max_length=30, verbose_name='Nom (pluriel)')),
                ('currency_singular', models.CharField(default='clé', max_length=30, verbose_name='Nom (singulier)')),
                ('daily_visit_award', models.PositiveIntegerField(default=10, help_text='Accordées après min_visit_minutes minutes passées sur le site', verbose_name='Clés / visite quotidienne')),
                ('min_visit_minutes', models.PositiveIntegerField(default=5, verbose_name='Durée minimale de visite (min)')),
                ('test_pass_award', models.PositiveIntegerField(default=1, verbose_name='Clés / test réussi')),
                ('keys_per_pack', models.PositiveIntegerField(default=10, verbose_name='Coût en clés / pack de questions')),
                ('questions_per_pack', models.PositiveIntegerField(default=10, verbose_name='Questions ajoutées / pack')),
                ('inactivity_grace_days', models.PositiveIntegerField(default=3, verbose_name='Jours de grâce avant pénalité')),
                ('decay_per_day', models.PositiveIntegerField(default=10, verbose_name="Clés retirées / jour d'inactivité (après grâce)")),
            ],
            options={
                'verbose_name': 'Paramètres des clés',
                'verbose_name_plural': 'Paramètres des clés',
            },
        ),
        migrations.CreateModel(
            name='KeyWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.PositiveIntegerField(default=0, verbose_name='Solde (clés)')),
                ('last_active_date', models.DateField(blank=True, null=True, verbose_name='Dernière activité')),
                ('today_minutes', models.PositiveSmallIntegerField(default=0, verbose_name="Minutes aujourd'hui")),
                ('awarded_today', models.BooleanField(default=False, verbose_name="Clés accordées aujourd'hui")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='key_wallet', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Portefeuille',
                'verbose_name_plural': 'Portefeuilles',
            },
        ),
        migrations.CreateModel(
            name='KeyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Montant')),
                ('reason', models.CharField(choices=[('daily_visit', 'Visite quotidienne'), ('test_pass', 'Test réussi'), ('purchase_bonus', 'Bonus achat'), ('spend_questions', 'Échange questions'), ('decay', 'Pénalité inactivité'), ('admin', 'Ajustement admin')], max_length=30, verbose_name='Raison')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Note')),
                ('balance_after', models.PositiveIntegerField(default=0, verbose_name='Solde après')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='rewards.keywallet', verbose_name='Portefeuille')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
