# Generated by Django 6.0.2 on 2026-03-08 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0002_tank_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keysettings',
            options={'verbose_name': 'Paramètres du réservoir', 'verbose_name_plural': 'Paramètres du réservoir'},
        ),
        migrations.AlterField(
            model_name='keysettings',
            name='currency_plural',
            field=models.CharField(default='litres', max_length=30, verbose_name='Nom (pluriel)'),
        ),
        migrations.AlterField(
            model_name='keysettings',
            name='currency_singular',
            field=models.CharField(default='litre', max_length=30, verbose_name='Nom (singulier)'),
        ),
        migrations.AlterField(
            model_name='keysettings',
            name='daily_visit_award',
            field=models.PositiveIntegerField(default=10, help_text='Accordés après min_visit_minutes minutes passées sur le site', verbose_name='Litres / visite quotidienne'),
        ),
        migrations.AlterField(
            model_name='keysettings',
            name='icon',
            field=models.CharField(default='⛽', help_text='Emoji ou caractère affiché comme monnaie', max_length=10, verbose_name='Icône'),
        ),
        migrations.AlterField(
            model_name='keysettings',
            name='keys_per_pack',
            field=models.PositiveIntegerField(default=20, editable=False, verbose_name='Coût / pack (legacy)'),
        ),
        migrations.AlterField(
            model_name='keysettings',
            name='questions_per_pack',
            field=models.PositiveIntegerField(default=10, editable=False, verbose_name='Questions / pack (legacy)'),
        ),
        migrations.AlterField(
            model_name='keysettings',
            name='test_pass_award',
            field=models.PositiveIntegerField(default=5, verbose_name='Litres / test réussi'),
        ),
    ]
