# Generated by Django 6.0.2 on 2026-02-27 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RuleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nom (FR)')),
                ('name_nl', models.CharField(blank=True, max_length=150, verbose_name='Naam (NL)')),
                ('name_ru', models.CharField(blank=True, max_length=150, verbose_name='Название (RU)')),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(blank=True, help_text="Nom de l'icône (ex: shield, alert-triangle)", max_length=50, verbose_name='Icône')),
                ('description', models.TextField(blank=True, verbose_name='Description (FR)')),
                ('description_nl', models.TextField(blank=True, verbose_name='Beschrijving (NL)')),
                ('description_ru', models.TextField(blank=True, verbose_name='Описание (RU)')),
                ('order', models.IntegerField(default=0, verbose_name='Ordre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Catégorie règles',
                'verbose_name_plural': 'Catégories règles',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CodeArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_number', models.CharField(help_text='Ex: Art. 12.1.1', max_length=30, verbose_name="Numéro d'article")),
                ('title', models.CharField(max_length=250, verbose_name='Titre (FR)')),
                ('title_nl', models.CharField(blank=True, max_length=250, verbose_name='Titel (NL)')),
                ('title_ru', models.CharField(blank=True, max_length=250, verbose_name='Заголовок (RU)')),
                ('content', models.TextField(verbose_name='Contenu (FR)')),
                ('content_nl', models.TextField(blank=True, verbose_name='Inhoud (NL)')),
                ('content_ru', models.TextField(blank=True, verbose_name='Содержание (RU)')),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('is_free', models.BooleanField(default=True, help_text='Visible sans abonnement premium.', verbose_name='Gratuit')),
                ('order', models.IntegerField(default=0, verbose_name='Ordre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='reglementation.rulecategory', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Article du code',
                'verbose_name_plural': 'Articles du code',
                'ordering': ['order', 'article_number'],
            },
        ),
        migrations.CreateModel(
            name='TrafficSign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Ex: C1, E1, F50', max_length=20, unique=True, verbose_name='Code')),
                ('sign_type', models.CharField(choices=[('danger', 'Danger'), ('interdiction', 'Interdiction'), ('obligation', 'Obligation'), ('indication', 'Indication'), ('priorite', 'Priorité'), ('directionnel', 'Directionnel'), ('additionnel', 'Additionnel')], default='indication', max_length=20, verbose_name='Type')),
                ('name', models.CharField(max_length=200, verbose_name='Nom (FR)')),
                ('name_nl', models.CharField(blank=True, max_length=200, verbose_name='Naam (NL)')),
                ('name_ru', models.CharField(blank=True, max_length=200, verbose_name='Название (RU)')),
                ('description', models.TextField(blank=True, verbose_name='Description (FR)')),
                ('description_nl', models.TextField(blank=True, verbose_name='Beschrijving (NL)')),
                ('description_ru', models.TextField(blank=True, verbose_name='Описание (RU)')),
                ('image', models.ImageField(blank=True, upload_to='signs/', verbose_name='Image')),
                ('order', models.IntegerField(default=0, verbose_name='Ordre')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signs', to='reglementation.rulecategory', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Panneau de signalisation',
                'verbose_name_plural': 'Panneaux de signalisation',
                'ordering': ['sign_type', 'order', 'code'],
            },
        ),
    ]
