# Generated by Django 6.0.2 on 2026-02-27 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reglementation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codearticle',
            name='content_text',
            field=models.TextField(blank=True, help_text='Version texte pour la recherche.', verbose_name='Texte brut'),
        ),
        migrations.AlterField(
            model_name='codearticle',
            name='content',
            field=models.TextField(blank=True, verbose_name='Contenu (FR)'),
        ),
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='reglementation/', verbose_name='Image')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='Texte alternatif')),
                ('sign_code', models.CharField(blank=True, help_text='Ex: C1, D7, F17', max_length=20, verbose_name='Code panneau')),
                ('order', models.IntegerField(default=0, verbose_name='Ordre')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='reglementation.codearticle', verbose_name='Article')),
            ],
            options={
                'verbose_name': "Image d'article",
                'verbose_name_plural': "Images d'articles",
                'ordering': ['order'],
            },
        ),
    ]
