# Generated by Django 6.0.2 on 2026-03-04 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reglementation', '0002_codearticle_content_text_alter_codearticle_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codearticle',
            name='law_id',
            field=models.CharField(db_index=True, default='1975', help_text='ID de la loi source (ex: 1975, 1968, 2005)', max_length=20, verbose_name='Loi'),
        ),
        migrations.AddField(
            model_name='rulecategory',
            name='law_id',
            field=models.CharField(db_index=True, default='1975', help_text='ID de la loi source (ex: 1975, 1968, 2005)', max_length=20, verbose_name='Loi'),
        ),
        migrations.AddIndex(
            model_name='codearticle',
            index=models.Index(fields=['law_id', 'article_number'], name='reglementat_law_id_e34134_idx'),
        ),
    ]
