# Generated by Django 6.0.2 on 2026-03-05 12:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=20, unique=True, verbose_name='Clé')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('duration_days', models.PositiveIntegerField(default=0, help_text='0 = gratuit/illimité', verbose_name='Durée (jours)')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Prix (€)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('is_highlighted', models.BooleanField(default=False, verbose_name='Mis en avant')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Ordre')),
            ],
            options={
                'verbose_name': 'Forfait',
                'verbose_name_plural': 'Forfaits',
                'ordering': ['sort_order', 'price'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Montant (€)')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('paid', 'Payé'), ('failed', 'Échoué'), ('expired', 'Expiré'), ('canceled', 'Annulé')], default='pending', max_length=20, verbose_name='Statut')),
                ('mollie_payment_id', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='ID Mollie')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Payé le')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='shop.plan', verbose_name='Forfait')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-created_at'],
            },
        ),
    ]
