# Generated by Django 6.0.2 on 2026-03-05 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='key_bonus',
            field=models.PositiveIntegerField(default=0, help_text="Clés accordées à l'achat de ce forfait (0 = aucun bonus)", verbose_name='Bonus clés 🔑'),
        ),
    ]
