# Generated by Django 6.0.2 on 2026-02-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('subject', models.CharField(max_length=200, verbose_name='Sujet')),
                ('message', models.TextField(verbose_name='Message')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Message de contact',
                'verbose_name_plural': 'Messages de contact',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Glossary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=200, verbose_name='Terme (FR)')),
                ('term_nl', models.CharField(blank=True, max_length=200, verbose_name='Term (NL)')),
                ('term_ru', models.CharField(blank=True, max_length=200, verbose_name='Термин (RU)')),
                ('definition', models.TextField(verbose_name='Définition (FR)')),
                ('definition_nl', models.TextField(blank=True, verbose_name='Definitie (NL)')),
                ('definition_ru', models.TextField(blank=True, verbose_name='Определение (RU)')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Catégorie')),
                ('order', models.IntegerField(default=0, verbose_name='Ordre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Terme du glossaire',
                'verbose_name_plural': 'Glossaire',
                'ordering': ['order', 'term'],
            },
        ),
    ]
